# Generated by Django 3.1.7 on 2021-09-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoGeografia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ubicacion', models.CharField(max_length=200)),
                ('TipoGeografia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoGeografia.tipogeografia')),
            ],
        ),
    ]
