# Generated by Django 3.1.7 on 2021-09-16 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoCliente', '0001_initial'),
        ('TipoIdentificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=200)),
                ('numeroIdentificacion', models.CharField(max_length=200)),
                ('TipoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoCliente.tipocliente')),
                ('TipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoIdentificacion.tipoidentificacion')),
            ],
        ),
    ]
