# Generated by Django 3.1.7 on 2021-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='NombreCliente',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
